[versions]
activityComposeVersion = "1.9.3"
agp = "8.13.0"
androidxComposeBom = "2024.10.01"
cameraX = "1.3.4"
coilCompose = "2.7.0"
core = "3.3.0"
itextg = "5.5.10"
junitJupiterApi = "5.11.0"
junitJupiterEngine = "5.11.0"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
kotlinTest = "2.2.20"
lifecycleRuntimeKtx = "2.9.3"
activityCompose = "1.11.0"
composeBom = "2024.09.00"
materialIconsExtendedAndroidVersion = "1.6.7"
mockk = "1.14.6"
opencv = "4.12.0"
composeBomVersion = "2025.09.00"
material3 = "1.5.0-alpha04"
opencvAndroid = "4.5.1"
opencvVersion = "4.9.0-0"
tessTwo = "9.1.0"
ui = "1.10.0-alpha03"
foundation = "1.10.0-alpha03"
uiToolingPreview = "1.10.0-alpha03"
uiTooling = "1.10.0-alpha03"
navigationCompose = "2.9.5"
materialIconsExtendedAndroid = "1.7.8"
material = "1.10.0-alpha05"
materialVersion = "1.14.0-alpha05"
jetbrainsKotlinJvm = "2.0.21"
appcompat = "1.7.1"
mlkitTextRecognition = "16.0.0"
kotlinxCoroutines = "1.8.1"

[libraries]
androidx-activity-compose-v193 = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "cameraX" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "cameraX" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "cameraX" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "cameraX" }
androidx-compose-bom-v20241001 = { module = "androidx.compose:compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-material-icons-extended-android-v167 = { module = "androidx.compose.material:material-icons-extended-android", version.ref = "materialIconsExtendedAndroidVersion" }
androidx-compose-material3-material3 = { module = "androidx.compose.material3:material3" }
androidx-compose-ui-ui = { module = "androidx.compose.ui:ui" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
core = { module = "com.afollestad.material-dialogs:core", version.ref = "core" }
itextg = { module = "com.itextpdf:itextg", version.ref = "itextg" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiterApi" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junitJupiterEngine" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlinTest" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
opencv = { module = "org.opencv:opencv", version.ref = "opencv" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBomVersion" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
opencv-android = { module = "org.opencv:opencv-android", version.ref = "opencvAndroid" }
openpnp-opencv = { module = "org.openpnp:opencv", version.ref = "opencvVersion" }
tess-two = { module = "com.rmtheis:tess-two", version.ref = "tessTwo" }
ui = { group = "androidx.compose.ui", name = "ui", version.ref = "ui" }
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-ui-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version.ref = "uiToolingPreview" }
androidx-compose-ui-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
androidx-material-icons-extended-android = { group = "androidx.compose.material", name = "material-icons-extended-android", version.ref = "materialIconsExtendedAndroid" }
androidx-material = { group = "androidx.compose.material", name = "material", version.ref = "material" }
material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
mlkit-text-recognition = { module = "com.google.mlkit:text-recognition", version.ref = "mlkitTextRecognition" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
android-library = { id = "com.android.library", version.ref = "agp" }

